// GENERATED by scripts/gen-tokens.mjs — do not edit. Source: docs/design-tokens.json

export const BREAKPOINT_DESKTOP = 1280;

/** Spec 018: below this width the desktop third column overlays the list. */
export const BREAKPOINT_CONTACTS_OVERLAY = 1120;

export const CONTROL = { sm: 36, md: 44, lg: 52 } as const;

export const FONT_UI = "'Plus Jakarta Sans', 'Noto Sans SC', system-ui, sans-serif";

export const FONT_MONO = "'IBM Plex Mono', ui-monospace, SFMono-Regular, monospace";

export const MOTION = { fast: 150, base: 250, slow: 400 } as const;

/** Web addition: CTA label color on accent surfaces, both modes (see tokens.css). */
export const ON_ACCENT = '#FFFFFF';

/** Raw per-mode color tables (path -> value) for the contrast gate. */
export const COLORS = {
	light: {
		'color.fg.base': '#1A1A18',
		'color.fg.muted': '#6E6B62',
		'color.fg.subtle': '#8C887E',
		'color.fg.inverse': '#FFFFFF',
		'color.bg.base': '#FAFAF8',
		'color.bg.raised': '#FFFFFF',
		'color.bg.sunken': '#F5F3EF',
		'color.accent.base': '#E8572A',
		'color.accent.soft': '#FFF0EB',
		'color.success.base': '#2D8E5F',
		'color.success.soft': '#EDFAF2',
		'color.warning.base': '#92600A',
		'color.warning.soft': '#FFF8F0',
		'color.warning.border': '#F0DCC8',
		'color.error.base': '#C62828',
		'color.error.soft': '#FEF2F2',
		'color.info.base': '#4267F4',
		'color.info.soft': '#EDF0FF',
		'color.border.base': '#ECEBE4',
		'color.border.strong': '#D8D6CE',
		'color.fixed.shadowInk': '#1A1A18',
		'color.fixed.backdrop': 'rgba(0,0,0,0.35)',
		'color.fixed.focusRingInner': '#FAFAF8',
		'color.fixed.focusRingOuter': '#E8572A',
		'color.fixed.desktopCanvas': '#E8E8E8',
		'color.fixed.splashBg': '#1A1A18',
		'color.fixed.androidAdaptiveIconBg': '#0A1929'
	},
	dark: {
		'color.fg.base': '#E8E6E1',
		'color.fg.muted': '#9A9790',
		'color.fg.subtle': '#85827A',
		'color.fg.inverse': '#1A1A18',
		'color.bg.base': '#141412',
		'color.bg.raised': '#1E1E1B',
		'color.bg.sunken': '#0F0F0D',
		'color.accent.base': '#E8572A',
		'color.accent.soft': '#2C1A12',
		'color.success.base': '#3DA872',
		'color.success.soft': '#132A1E',
		'color.warning.base': '#D4A54A',
		'color.warning.soft': '#2A2010',
		'color.warning.border': '#3D3020',
		'color.error.base': '#F87171',
		'color.error.soft': '#2D1515',
		'color.info.base': '#5A7CF6',
		'color.info.soft': '#131B33',
		'color.border.base': '#2C2C28',
		'color.border.strong': '#3E3E38',
		'color.fixed.shadowInk': '#1A1A18',
		'color.fixed.backdrop': 'rgba(0,0,0,0.35)',
		'color.fixed.focusRingInner': '#141412',
		'color.fixed.focusRingOuter': '#E8572A',
		'color.fixed.desktopCanvas': '#E8E8E8',
		'color.fixed.splashBg': '#1A1A18',
		'color.fixed.androidAdaptiveIconBg': '#0A1929'
	}
} as const;
