/**
 * GENERATED by scripts/gen-i18n.mjs — do not edit by hand.
 *
 * Per-language resource aggregator. Each language merges its core file
 * (common/language/settings) + every per-namespace file into one flat
 * `translation` object, in the order below — a later namespace overwriting an
 * earlier key behaves exactly as it always has.
 *
 * The corpus itself lives in the Rust crate (`rust/crates/vela-core/i18n/locales`),
 * which is the single source of truth for every platform: edit a string there and
 * regenerate, and the TypeScript resources, the compiled-in Rust catalogs and the
 * conformance corpus all move together.
 *
 * `en` is exported BY NAME because src/i18n/i18next.d.ts derives the typed key
 * union from it (`import type { en } from './resources'`).
 *
 * To add a language: add it to LOCALES in scripts/gen-i18n.mjs and re-run
 * `npm run gen:i18n`.
 */
import enCore from '../../rust/crates/vela-core/i18n/locales/en.json';
import enHome from '../../rust/crates/vela-core/i18n/locales/en/home.json';
import enSend from '../../rust/crates/vela-core/i18n/locales/en/send.json';
import enReceive from '../../rust/crates/vela-core/i18n/locales/en/receive.json';
import enAssets from '../../rust/crates/vela-core/i18n/locales/en/assets.json';
import enAddToken from '../../rust/crates/vela-core/i18n/locales/en/addToken.json';
import enTokenDetail from '../../rust/crates/vela-core/i18n/locales/en/tokenDetail.json';
import enHistory from '../../rust/crates/vela-core/i18n/locales/en/history.json';
import enOnboarding from '../../rust/crates/vela-core/i18n/locales/en/onboarding.json';
import enConnect from '../../rust/crates/vela-core/i18n/locales/en/connect.json';
import enAbout from '../../rust/crates/vela-core/i18n/locales/en/about.json';
import enClearSigning from '../../rust/crates/vela-core/i18n/locales/en/clearSigning.json';
import enComponentsTx from '../../rust/crates/vela-core/i18n/locales/en/componentsTx.json';
import enComponentsUi from '../../rust/crates/vela-core/i18n/locales/en/componentsUi.json';
import enSettingsModals from '../../rust/crates/vela-core/i18n/locales/en/settingsModals.json';
import enContacts from '../../rust/crates/vela-core/i18n/locales/en/contacts.json';
import enExplore from '../../rust/crates/vela-core/i18n/locales/en/explore.json';
import zhCore from '../../rust/crates/vela-core/i18n/locales/zh.json';
import zhHome from '../../rust/crates/vela-core/i18n/locales/zh/home.json';
import zhSend from '../../rust/crates/vela-core/i18n/locales/zh/send.json';
import zhReceive from '../../rust/crates/vela-core/i18n/locales/zh/receive.json';
import zhAssets from '../../rust/crates/vela-core/i18n/locales/zh/assets.json';
import zhAddToken from '../../rust/crates/vela-core/i18n/locales/zh/addToken.json';
import zhTokenDetail from '../../rust/crates/vela-core/i18n/locales/zh/tokenDetail.json';
import zhHistory from '../../rust/crates/vela-core/i18n/locales/zh/history.json';
import zhOnboarding from '../../rust/crates/vela-core/i18n/locales/zh/onboarding.json';
import zhConnect from '../../rust/crates/vela-core/i18n/locales/zh/connect.json';
import zhAbout from '../../rust/crates/vela-core/i18n/locales/zh/about.json';
import zhClearSigning from '../../rust/crates/vela-core/i18n/locales/zh/clearSigning.json';
import zhComponentsTx from '../../rust/crates/vela-core/i18n/locales/zh/componentsTx.json';
import zhComponentsUi from '../../rust/crates/vela-core/i18n/locales/zh/componentsUi.json';
import zhSettingsModals from '../../rust/crates/vela-core/i18n/locales/zh/settingsModals.json';
import zhContacts from '../../rust/crates/vela-core/i18n/locales/zh/contacts.json';
import zhExplore from '../../rust/crates/vela-core/i18n/locales/zh/explore.json';
import zhTWCore from '../../rust/crates/vela-core/i18n/locales/zh-TW.json';
import zhTWHome from '../../rust/crates/vela-core/i18n/locales/zh-TW/home.json';
import zhTWSend from '../../rust/crates/vela-core/i18n/locales/zh-TW/send.json';
import zhTWReceive from '../../rust/crates/vela-core/i18n/locales/zh-TW/receive.json';
import zhTWAssets from '../../rust/crates/vela-core/i18n/locales/zh-TW/assets.json';
import zhTWAddToken from '../../rust/crates/vela-core/i18n/locales/zh-TW/addToken.json';
import zhTWTokenDetail from '../../rust/crates/vela-core/i18n/locales/zh-TW/tokenDetail.json';
import zhTWHistory from '../../rust/crates/vela-core/i18n/locales/zh-TW/history.json';
import zhTWOnboarding from '../../rust/crates/vela-core/i18n/locales/zh-TW/onboarding.json';
import zhTWConnect from '../../rust/crates/vela-core/i18n/locales/zh-TW/connect.json';
import zhTWAbout from '../../rust/crates/vela-core/i18n/locales/zh-TW/about.json';
import zhTWClearSigning from '../../rust/crates/vela-core/i18n/locales/zh-TW/clearSigning.json';
import zhTWComponentsTx from '../../rust/crates/vela-core/i18n/locales/zh-TW/componentsTx.json';
import zhTWComponentsUi from '../../rust/crates/vela-core/i18n/locales/zh-TW/componentsUi.json';
import zhTWSettingsModals from '../../rust/crates/vela-core/i18n/locales/zh-TW/settingsModals.json';
import zhTWContacts from '../../rust/crates/vela-core/i18n/locales/zh-TW/contacts.json';
import zhTWExplore from '../../rust/crates/vela-core/i18n/locales/zh-TW/explore.json';
import zhHKCore from '../../rust/crates/vela-core/i18n/locales/zh-HK.json';
import zhHKHome from '../../rust/crates/vela-core/i18n/locales/zh-HK/home.json';
import zhHKSend from '../../rust/crates/vela-core/i18n/locales/zh-HK/send.json';
import zhHKReceive from '../../rust/crates/vela-core/i18n/locales/zh-HK/receive.json';
import zhHKAssets from '../../rust/crates/vela-core/i18n/locales/zh-HK/assets.json';
import zhHKAddToken from '../../rust/crates/vela-core/i18n/locales/zh-HK/addToken.json';
import zhHKTokenDetail from '../../rust/crates/vela-core/i18n/locales/zh-HK/tokenDetail.json';
import zhHKHistory from '../../rust/crates/vela-core/i18n/locales/zh-HK/history.json';
import zhHKOnboarding from '../../rust/crates/vela-core/i18n/locales/zh-HK/onboarding.json';
import zhHKConnect from '../../rust/crates/vela-core/i18n/locales/zh-HK/connect.json';
import zhHKAbout from '../../rust/crates/vela-core/i18n/locales/zh-HK/about.json';
import zhHKClearSigning from '../../rust/crates/vela-core/i18n/locales/zh-HK/clearSigning.json';
import zhHKComponentsTx from '../../rust/crates/vela-core/i18n/locales/zh-HK/componentsTx.json';
import zhHKComponentsUi from '../../rust/crates/vela-core/i18n/locales/zh-HK/componentsUi.json';
import zhHKSettingsModals from '../../rust/crates/vela-core/i18n/locales/zh-HK/settingsModals.json';
import zhHKContacts from '../../rust/crates/vela-core/i18n/locales/zh-HK/contacts.json';
import zhHKExplore from '../../rust/crates/vela-core/i18n/locales/zh-HK/explore.json';
import jaCore from '../../rust/crates/vela-core/i18n/locales/ja.json';
import jaHome from '../../rust/crates/vela-core/i18n/locales/ja/home.json';
import jaSend from '../../rust/crates/vela-core/i18n/locales/ja/send.json';
import jaReceive from '../../rust/crates/vela-core/i18n/locales/ja/receive.json';
import jaAssets from '../../rust/crates/vela-core/i18n/locales/ja/assets.json';
import jaAddToken from '../../rust/crates/vela-core/i18n/locales/ja/addToken.json';
import jaTokenDetail from '../../rust/crates/vela-core/i18n/locales/ja/tokenDetail.json';
import jaHistory from '../../rust/crates/vela-core/i18n/locales/ja/history.json';
import jaOnboarding from '../../rust/crates/vela-core/i18n/locales/ja/onboarding.json';
import jaConnect from '../../rust/crates/vela-core/i18n/locales/ja/connect.json';
import jaAbout from '../../rust/crates/vela-core/i18n/locales/ja/about.json';
import jaClearSigning from '../../rust/crates/vela-core/i18n/locales/ja/clearSigning.json';
import jaComponentsTx from '../../rust/crates/vela-core/i18n/locales/ja/componentsTx.json';
import jaComponentsUi from '../../rust/crates/vela-core/i18n/locales/ja/componentsUi.json';
import jaSettingsModals from '../../rust/crates/vela-core/i18n/locales/ja/settingsModals.json';
import jaContacts from '../../rust/crates/vela-core/i18n/locales/ja/contacts.json';
import jaExplore from '../../rust/crates/vela-core/i18n/locales/ja/explore.json';
import koCore from '../../rust/crates/vela-core/i18n/locales/ko.json';
import koHome from '../../rust/crates/vela-core/i18n/locales/ko/home.json';
import koSend from '../../rust/crates/vela-core/i18n/locales/ko/send.json';
import koReceive from '../../rust/crates/vela-core/i18n/locales/ko/receive.json';
import koAssets from '../../rust/crates/vela-core/i18n/locales/ko/assets.json';
import koAddToken from '../../rust/crates/vela-core/i18n/locales/ko/addToken.json';
import koTokenDetail from '../../rust/crates/vela-core/i18n/locales/ko/tokenDetail.json';
import koHistory from '../../rust/crates/vela-core/i18n/locales/ko/history.json';
import koOnboarding from '../../rust/crates/vela-core/i18n/locales/ko/onboarding.json';
import koConnect from '../../rust/crates/vela-core/i18n/locales/ko/connect.json';
import koAbout from '../../rust/crates/vela-core/i18n/locales/ko/about.json';
import koClearSigning from '../../rust/crates/vela-core/i18n/locales/ko/clearSigning.json';
import koComponentsTx from '../../rust/crates/vela-core/i18n/locales/ko/componentsTx.json';
import koComponentsUi from '../../rust/crates/vela-core/i18n/locales/ko/componentsUi.json';
import koSettingsModals from '../../rust/crates/vela-core/i18n/locales/ko/settingsModals.json';
import koContacts from '../../rust/crates/vela-core/i18n/locales/ko/contacts.json';
import koExplore from '../../rust/crates/vela-core/i18n/locales/ko/explore.json';
import viCore from '../../rust/crates/vela-core/i18n/locales/vi.json';
import viHome from '../../rust/crates/vela-core/i18n/locales/vi/home.json';
import viSend from '../../rust/crates/vela-core/i18n/locales/vi/send.json';
import viReceive from '../../rust/crates/vela-core/i18n/locales/vi/receive.json';
import viAssets from '../../rust/crates/vela-core/i18n/locales/vi/assets.json';
import viAddToken from '../../rust/crates/vela-core/i18n/locales/vi/addToken.json';
import viTokenDetail from '../../rust/crates/vela-core/i18n/locales/vi/tokenDetail.json';
import viHistory from '../../rust/crates/vela-core/i18n/locales/vi/history.json';
import viOnboarding from '../../rust/crates/vela-core/i18n/locales/vi/onboarding.json';
import viConnect from '../../rust/crates/vela-core/i18n/locales/vi/connect.json';
import viAbout from '../../rust/crates/vela-core/i18n/locales/vi/about.json';
import viClearSigning from '../../rust/crates/vela-core/i18n/locales/vi/clearSigning.json';
import viComponentsTx from '../../rust/crates/vela-core/i18n/locales/vi/componentsTx.json';
import viComponentsUi from '../../rust/crates/vela-core/i18n/locales/vi/componentsUi.json';
import viSettingsModals from '../../rust/crates/vela-core/i18n/locales/vi/settingsModals.json';
import viContacts from '../../rust/crates/vela-core/i18n/locales/vi/contacts.json';
import viExplore from '../../rust/crates/vela-core/i18n/locales/vi/explore.json';
import idCore from '../../rust/crates/vela-core/i18n/locales/id.json';
import idHome from '../../rust/crates/vela-core/i18n/locales/id/home.json';
import idSend from '../../rust/crates/vela-core/i18n/locales/id/send.json';
import idReceive from '../../rust/crates/vela-core/i18n/locales/id/receive.json';
import idAssets from '../../rust/crates/vela-core/i18n/locales/id/assets.json';
import idAddToken from '../../rust/crates/vela-core/i18n/locales/id/addToken.json';
import idTokenDetail from '../../rust/crates/vela-core/i18n/locales/id/tokenDetail.json';
import idHistory from '../../rust/crates/vela-core/i18n/locales/id/history.json';
import idOnboarding from '../../rust/crates/vela-core/i18n/locales/id/onboarding.json';
import idConnect from '../../rust/crates/vela-core/i18n/locales/id/connect.json';
import idAbout from '../../rust/crates/vela-core/i18n/locales/id/about.json';
import idClearSigning from '../../rust/crates/vela-core/i18n/locales/id/clearSigning.json';
import idComponentsTx from '../../rust/crates/vela-core/i18n/locales/id/componentsTx.json';
import idComponentsUi from '../../rust/crates/vela-core/i18n/locales/id/componentsUi.json';
import idSettingsModals from '../../rust/crates/vela-core/i18n/locales/id/settingsModals.json';
import idContacts from '../../rust/crates/vela-core/i18n/locales/id/contacts.json';
import idExplore from '../../rust/crates/vela-core/i18n/locales/id/explore.json';
import trCore from '../../rust/crates/vela-core/i18n/locales/tr.json';
import trHome from '../../rust/crates/vela-core/i18n/locales/tr/home.json';
import trSend from '../../rust/crates/vela-core/i18n/locales/tr/send.json';
import trReceive from '../../rust/crates/vela-core/i18n/locales/tr/receive.json';
import trAssets from '../../rust/crates/vela-core/i18n/locales/tr/assets.json';
import trAddToken from '../../rust/crates/vela-core/i18n/locales/tr/addToken.json';
import trTokenDetail from '../../rust/crates/vela-core/i18n/locales/tr/tokenDetail.json';
import trHistory from '../../rust/crates/vela-core/i18n/locales/tr/history.json';
import trOnboarding from '../../rust/crates/vela-core/i18n/locales/tr/onboarding.json';
import trConnect from '../../rust/crates/vela-core/i18n/locales/tr/connect.json';
import trAbout from '../../rust/crates/vela-core/i18n/locales/tr/about.json';
import trClearSigning from '../../rust/crates/vela-core/i18n/locales/tr/clearSigning.json';
import trComponentsTx from '../../rust/crates/vela-core/i18n/locales/tr/componentsTx.json';
import trComponentsUi from '../../rust/crates/vela-core/i18n/locales/tr/componentsUi.json';
import trSettingsModals from '../../rust/crates/vela-core/i18n/locales/tr/settingsModals.json';
import trContacts from '../../rust/crates/vela-core/i18n/locales/tr/contacts.json';
import trExplore from '../../rust/crates/vela-core/i18n/locales/tr/explore.json';
import esMXCore from '../../rust/crates/vela-core/i18n/locales/es-MX.json';
import esMXHome from '../../rust/crates/vela-core/i18n/locales/es-MX/home.json';
import esMXSend from '../../rust/crates/vela-core/i18n/locales/es-MX/send.json';
import esMXReceive from '../../rust/crates/vela-core/i18n/locales/es-MX/receive.json';
import esMXAssets from '../../rust/crates/vela-core/i18n/locales/es-MX/assets.json';
import esMXAddToken from '../../rust/crates/vela-core/i18n/locales/es-MX/addToken.json';
import esMXTokenDetail from '../../rust/crates/vela-core/i18n/locales/es-MX/tokenDetail.json';
import esMXHistory from '../../rust/crates/vela-core/i18n/locales/es-MX/history.json';
import esMXOnboarding from '../../rust/crates/vela-core/i18n/locales/es-MX/onboarding.json';
import esMXConnect from '../../rust/crates/vela-core/i18n/locales/es-MX/connect.json';
import esMXAbout from '../../rust/crates/vela-core/i18n/locales/es-MX/about.json';
import esMXClearSigning from '../../rust/crates/vela-core/i18n/locales/es-MX/clearSigning.json';
import esMXComponentsTx from '../../rust/crates/vela-core/i18n/locales/es-MX/componentsTx.json';
import esMXComponentsUi from '../../rust/crates/vela-core/i18n/locales/es-MX/componentsUi.json';
import esMXSettingsModals from '../../rust/crates/vela-core/i18n/locales/es-MX/settingsModals.json';
import esMXContacts from '../../rust/crates/vela-core/i18n/locales/es-MX/contacts.json';
import esMXExplore from '../../rust/crates/vela-core/i18n/locales/es-MX/explore.json';
import ptBRCore from '../../rust/crates/vela-core/i18n/locales/pt-BR.json';
import ptBRHome from '../../rust/crates/vela-core/i18n/locales/pt-BR/home.json';
import ptBRSend from '../../rust/crates/vela-core/i18n/locales/pt-BR/send.json';
import ptBRReceive from '../../rust/crates/vela-core/i18n/locales/pt-BR/receive.json';
import ptBRAssets from '../../rust/crates/vela-core/i18n/locales/pt-BR/assets.json';
import ptBRAddToken from '../../rust/crates/vela-core/i18n/locales/pt-BR/addToken.json';
import ptBRTokenDetail from '../../rust/crates/vela-core/i18n/locales/pt-BR/tokenDetail.json';
import ptBRHistory from '../../rust/crates/vela-core/i18n/locales/pt-BR/history.json';
import ptBROnboarding from '../../rust/crates/vela-core/i18n/locales/pt-BR/onboarding.json';
import ptBRConnect from '../../rust/crates/vela-core/i18n/locales/pt-BR/connect.json';
import ptBRAbout from '../../rust/crates/vela-core/i18n/locales/pt-BR/about.json';
import ptBRClearSigning from '../../rust/crates/vela-core/i18n/locales/pt-BR/clearSigning.json';
import ptBRComponentsTx from '../../rust/crates/vela-core/i18n/locales/pt-BR/componentsTx.json';
import ptBRComponentsUi from '../../rust/crates/vela-core/i18n/locales/pt-BR/componentsUi.json';
import ptBRSettingsModals from '../../rust/crates/vela-core/i18n/locales/pt-BR/settingsModals.json';
import ptBRContacts from '../../rust/crates/vela-core/i18n/locales/pt-BR/contacts.json';
import ptBRExplore from '../../rust/crates/vela-core/i18n/locales/pt-BR/explore.json';
import frCore from '../../rust/crates/vela-core/i18n/locales/fr.json';
import frHome from '../../rust/crates/vela-core/i18n/locales/fr/home.json';
import frSend from '../../rust/crates/vela-core/i18n/locales/fr/send.json';
import frReceive from '../../rust/crates/vela-core/i18n/locales/fr/receive.json';
import frAssets from '../../rust/crates/vela-core/i18n/locales/fr/assets.json';
import frAddToken from '../../rust/crates/vela-core/i18n/locales/fr/addToken.json';
import frTokenDetail from '../../rust/crates/vela-core/i18n/locales/fr/tokenDetail.json';
import frHistory from '../../rust/crates/vela-core/i18n/locales/fr/history.json';
import frOnboarding from '../../rust/crates/vela-core/i18n/locales/fr/onboarding.json';
import frConnect from '../../rust/crates/vela-core/i18n/locales/fr/connect.json';
import frAbout from '../../rust/crates/vela-core/i18n/locales/fr/about.json';
import frClearSigning from '../../rust/crates/vela-core/i18n/locales/fr/clearSigning.json';
import frComponentsTx from '../../rust/crates/vela-core/i18n/locales/fr/componentsTx.json';
import frComponentsUi from '../../rust/crates/vela-core/i18n/locales/fr/componentsUi.json';
import frSettingsModals from '../../rust/crates/vela-core/i18n/locales/fr/settingsModals.json';
import frContacts from '../../rust/crates/vela-core/i18n/locales/fr/contacts.json';
import frExplore from '../../rust/crates/vela-core/i18n/locales/fr/explore.json';
import deCore from '../../rust/crates/vela-core/i18n/locales/de.json';
import deHome from '../../rust/crates/vela-core/i18n/locales/de/home.json';
import deSend from '../../rust/crates/vela-core/i18n/locales/de/send.json';
import deReceive from '../../rust/crates/vela-core/i18n/locales/de/receive.json';
import deAssets from '../../rust/crates/vela-core/i18n/locales/de/assets.json';
import deAddToken from '../../rust/crates/vela-core/i18n/locales/de/addToken.json';
import deTokenDetail from '../../rust/crates/vela-core/i18n/locales/de/tokenDetail.json';
import deHistory from '../../rust/crates/vela-core/i18n/locales/de/history.json';
import deOnboarding from '../../rust/crates/vela-core/i18n/locales/de/onboarding.json';
import deConnect from '../../rust/crates/vela-core/i18n/locales/de/connect.json';
import deAbout from '../../rust/crates/vela-core/i18n/locales/de/about.json';
import deClearSigning from '../../rust/crates/vela-core/i18n/locales/de/clearSigning.json';
import deComponentsTx from '../../rust/crates/vela-core/i18n/locales/de/componentsTx.json';
import deComponentsUi from '../../rust/crates/vela-core/i18n/locales/de/componentsUi.json';
import deSettingsModals from '../../rust/crates/vela-core/i18n/locales/de/settingsModals.json';
import deContacts from '../../rust/crates/vela-core/i18n/locales/de/contacts.json';
import deExplore from '../../rust/crates/vela-core/i18n/locales/de/explore.json';
import ruCore from '../../rust/crates/vela-core/i18n/locales/ru.json';
import ruHome from '../../rust/crates/vela-core/i18n/locales/ru/home.json';
import ruSend from '../../rust/crates/vela-core/i18n/locales/ru/send.json';
import ruReceive from '../../rust/crates/vela-core/i18n/locales/ru/receive.json';
import ruAssets from '../../rust/crates/vela-core/i18n/locales/ru/assets.json';
import ruAddToken from '../../rust/crates/vela-core/i18n/locales/ru/addToken.json';
import ruTokenDetail from '../../rust/crates/vela-core/i18n/locales/ru/tokenDetail.json';
import ruHistory from '../../rust/crates/vela-core/i18n/locales/ru/history.json';
import ruOnboarding from '../../rust/crates/vela-core/i18n/locales/ru/onboarding.json';
import ruConnect from '../../rust/crates/vela-core/i18n/locales/ru/connect.json';
import ruAbout from '../../rust/crates/vela-core/i18n/locales/ru/about.json';
import ruClearSigning from '../../rust/crates/vela-core/i18n/locales/ru/clearSigning.json';
import ruComponentsTx from '../../rust/crates/vela-core/i18n/locales/ru/componentsTx.json';
import ruComponentsUi from '../../rust/crates/vela-core/i18n/locales/ru/componentsUi.json';
import ruSettingsModals from '../../rust/crates/vela-core/i18n/locales/ru/settingsModals.json';
import ruContacts from '../../rust/crates/vela-core/i18n/locales/ru/contacts.json';
import ruExplore from '../../rust/crates/vela-core/i18n/locales/ru/explore.json';
import itCore from '../../rust/crates/vela-core/i18n/locales/it.json';
import itHome from '../../rust/crates/vela-core/i18n/locales/it/home.json';
import itSend from '../../rust/crates/vela-core/i18n/locales/it/send.json';
import itReceive from '../../rust/crates/vela-core/i18n/locales/it/receive.json';
import itAssets from '../../rust/crates/vela-core/i18n/locales/it/assets.json';
import itAddToken from '../../rust/crates/vela-core/i18n/locales/it/addToken.json';
import itTokenDetail from '../../rust/crates/vela-core/i18n/locales/it/tokenDetail.json';
import itHistory from '../../rust/crates/vela-core/i18n/locales/it/history.json';
import itOnboarding from '../../rust/crates/vela-core/i18n/locales/it/onboarding.json';
import itConnect from '../../rust/crates/vela-core/i18n/locales/it/connect.json';
import itAbout from '../../rust/crates/vela-core/i18n/locales/it/about.json';
import itClearSigning from '../../rust/crates/vela-core/i18n/locales/it/clearSigning.json';
import itComponentsTx from '../../rust/crates/vela-core/i18n/locales/it/componentsTx.json';
import itComponentsUi from '../../rust/crates/vela-core/i18n/locales/it/componentsUi.json';
import itSettingsModals from '../../rust/crates/vela-core/i18n/locales/it/settingsModals.json';
import itContacts from '../../rust/crates/vela-core/i18n/locales/it/contacts.json';
import itExplore from '../../rust/crates/vela-core/i18n/locales/it/explore.json';

export const en = {
  ...enCore,
  ...enHome,
  ...enSend,
  ...enReceive,
  ...enAssets,
  ...enAddToken,
  ...enTokenDetail,
  ...enHistory,
  ...enOnboarding,
  ...enConnect,
  ...enAbout,
  ...enClearSigning,
  ...enComponentsTx,
  ...enComponentsUi,
  ...enSettingsModals,
  ...enContacts,
  ...enExplore,
};

const zh = {
  ...zhCore,
  ...zhHome,
  ...zhSend,
  ...zhReceive,
  ...zhAssets,
  ...zhAddToken,
  ...zhTokenDetail,
  ...zhHistory,
  ...zhOnboarding,
  ...zhConnect,
  ...zhAbout,
  ...zhClearSigning,
  ...zhComponentsTx,
  ...zhComponentsUi,
  ...zhSettingsModals,
  ...zhContacts,
  ...zhExplore,
};

const zhTW = {
  ...zhTWCore,
  ...zhTWHome,
  ...zhTWSend,
  ...zhTWReceive,
  ...zhTWAssets,
  ...zhTWAddToken,
  ...zhTWTokenDetail,
  ...zhTWHistory,
  ...zhTWOnboarding,
  ...zhTWConnect,
  ...zhTWAbout,
  ...zhTWClearSigning,
  ...zhTWComponentsTx,
  ...zhTWComponentsUi,
  ...zhTWSettingsModals,
  ...zhTWContacts,
  ...zhTWExplore,
};

const zhHK = {
  ...zhHKCore,
  ...zhHKHome,
  ...zhHKSend,
  ...zhHKReceive,
  ...zhHKAssets,
  ...zhHKAddToken,
  ...zhHKTokenDetail,
  ...zhHKHistory,
  ...zhHKOnboarding,
  ...zhHKConnect,
  ...zhHKAbout,
  ...zhHKClearSigning,
  ...zhHKComponentsTx,
  ...zhHKComponentsUi,
  ...zhHKSettingsModals,
  ...zhHKContacts,
  ...zhHKExplore,
};

const ja = {
  ...jaCore,
  ...jaHome,
  ...jaSend,
  ...jaReceive,
  ...jaAssets,
  ...jaAddToken,
  ...jaTokenDetail,
  ...jaHistory,
  ...jaOnboarding,
  ...jaConnect,
  ...jaAbout,
  ...jaClearSigning,
  ...jaComponentsTx,
  ...jaComponentsUi,
  ...jaSettingsModals,
  ...jaContacts,
  ...jaExplore,
};

const ko = {
  ...koCore,
  ...koHome,
  ...koSend,
  ...koReceive,
  ...koAssets,
  ...koAddToken,
  ...koTokenDetail,
  ...koHistory,
  ...koOnboarding,
  ...koConnect,
  ...koAbout,
  ...koClearSigning,
  ...koComponentsTx,
  ...koComponentsUi,
  ...koSettingsModals,
  ...koContacts,
  ...koExplore,
};

const vi = {
  ...viCore,
  ...viHome,
  ...viSend,
  ...viReceive,
  ...viAssets,
  ...viAddToken,
  ...viTokenDetail,
  ...viHistory,
  ...viOnboarding,
  ...viConnect,
  ...viAbout,
  ...viClearSigning,
  ...viComponentsTx,
  ...viComponentsUi,
  ...viSettingsModals,
  ...viContacts,
  ...viExplore,
};

const id = {
  ...idCore,
  ...idHome,
  ...idSend,
  ...idReceive,
  ...idAssets,
  ...idAddToken,
  ...idTokenDetail,
  ...idHistory,
  ...idOnboarding,
  ...idConnect,
  ...idAbout,
  ...idClearSigning,
  ...idComponentsTx,
  ...idComponentsUi,
  ...idSettingsModals,
  ...idContacts,
  ...idExplore,
};

const tr = {
  ...trCore,
  ...trHome,
  ...trSend,
  ...trReceive,
  ...trAssets,
  ...trAddToken,
  ...trTokenDetail,
  ...trHistory,
  ...trOnboarding,
  ...trConnect,
  ...trAbout,
  ...trClearSigning,
  ...trComponentsTx,
  ...trComponentsUi,
  ...trSettingsModals,
  ...trContacts,
  ...trExplore,
};

const esMX = {
  ...esMXCore,
  ...esMXHome,
  ...esMXSend,
  ...esMXReceive,
  ...esMXAssets,
  ...esMXAddToken,
  ...esMXTokenDetail,
  ...esMXHistory,
  ...esMXOnboarding,
  ...esMXConnect,
  ...esMXAbout,
  ...esMXClearSigning,
  ...esMXComponentsTx,
  ...esMXComponentsUi,
  ...esMXSettingsModals,
  ...esMXContacts,
  ...esMXExplore,
};

const ptBR = {
  ...ptBRCore,
  ...ptBRHome,
  ...ptBRSend,
  ...ptBRReceive,
  ...ptBRAssets,
  ...ptBRAddToken,
  ...ptBRTokenDetail,
  ...ptBRHistory,
  ...ptBROnboarding,
  ...ptBRConnect,
  ...ptBRAbout,
  ...ptBRClearSigning,
  ...ptBRComponentsTx,
  ...ptBRComponentsUi,
  ...ptBRSettingsModals,
  ...ptBRContacts,
  ...ptBRExplore,
};

const fr = {
  ...frCore,
  ...frHome,
  ...frSend,
  ...frReceive,
  ...frAssets,
  ...frAddToken,
  ...frTokenDetail,
  ...frHistory,
  ...frOnboarding,
  ...frConnect,
  ...frAbout,
  ...frClearSigning,
  ...frComponentsTx,
  ...frComponentsUi,
  ...frSettingsModals,
  ...frContacts,
  ...frExplore,
};

const de = {
  ...deCore,
  ...deHome,
  ...deSend,
  ...deReceive,
  ...deAssets,
  ...deAddToken,
  ...deTokenDetail,
  ...deHistory,
  ...deOnboarding,
  ...deConnect,
  ...deAbout,
  ...deClearSigning,
  ...deComponentsTx,
  ...deComponentsUi,
  ...deSettingsModals,
  ...deContacts,
  ...deExplore,
};

const ru = {
  ...ruCore,
  ...ruHome,
  ...ruSend,
  ...ruReceive,
  ...ruAssets,
  ...ruAddToken,
  ...ruTokenDetail,
  ...ruHistory,
  ...ruOnboarding,
  ...ruConnect,
  ...ruAbout,
  ...ruClearSigning,
  ...ruComponentsTx,
  ...ruComponentsUi,
  ...ruSettingsModals,
  ...ruContacts,
  ...ruExplore,
};

const it = {
  ...itCore,
  ...itHome,
  ...itSend,
  ...itReceive,
  ...itAssets,
  ...itAddToken,
  ...itTokenDetail,
  ...itHistory,
  ...itOnboarding,
  ...itConnect,
  ...itAbout,
  ...itClearSigning,
  ...itComponentsTx,
  ...itComponentsUi,
  ...itSettingsModals,
  ...itContacts,
  ...itExplore,
};

export const resources = {
  "en": { translation: en },
  "zh": { translation: zh },
  "zh-TW": { translation: zhTW },
  "zh-HK": { translation: zhHK },
  "ja": { translation: ja },
  "ko": { translation: ko },
  "vi": { translation: vi },
  "id": { translation: id },
  "tr": { translation: tr },
  "es-MX": { translation: esMX },
  "pt-BR": { translation: ptBR },
  "fr": { translation: fr },
  "de": { translation: de },
  "ru": { translation: ru },
  "it": { translation: it },
};
