#!/usr/bin/env node
/**
 * Build vela-core for the web app.
 *
 * Pipeline: wasm-pack (--target web) → size gate → base64-embed the module and
 * neutralize wasm-bindgen's `import.meta.url` fallback → emit rust/pkg-web/.
 *
 * Why base64 + synchronous initSync instead of shipping a .wasm asset
 * (specs/001-rust-core-bindings/research.md D7):
 *   - metro 0.83 has no wasm-as-ESM support, so `--target bundler` is out;
 *   - `wrangler pages deploy` DROPS any path containing node_modules, which is
 *     exactly why scripts/fix-cf-pages-assets.js exists — a .wasm asset would
 *     have to survive that rewrite;
 *   - metro chokes on `import.meta` (see src/components/QRScanner.tsx:70),
 *     which the --target web glue emits as its default module path;
 *   - synchronous init means the facade needs no async gate before first use.
 *
 * Usage:
 *   node rust/scripts/build-web.mjs           build and write rust/pkg-web/
 *   node rust/scripts/build-web.mjs --check   verify the committed output is
 *                                             current (CI); non-zero on drift
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const RUST_DIR = dirname(dirname(fileURLToPath(import.meta.url)));
const CRATE_DIR = join(RUST_DIR, 'crates', 'vela-core-wasm');
const STAGING_DIR = join(RUST_DIR, 'target', 'pkg-web-staging');
const OUT_DIR = join(RUST_DIR, 'pkg-web');

/**
 * Hard ceiling on the wasm-opt'd module. Base64 inflates by 4/3 and the result
 * lands in the main web bundle, so growth past this means switching to the
 * async public/-dir route (research.md D7 fallback) rather than shipping a
 * multi-MB string.
 */
const MAX_WASM_BYTES = 1_000_000;

const CHECK_ONLY = process.argv.includes('--check');

function buildWasm() {
  if (existsSync(STAGING_DIR)) rmSync(STAGING_DIR, { recursive: true, force: true });
  // Panic-location strings from registry crates otherwise embed the builder's
  // absolute $CARGO_HOME (56 of them). That makes the artifact machine-dependent
  // — so `--check` could never pass on a CI runner — and ships a developer's
  // home directory to wallet.getvela.app. Remap so any machine produces the
  // same bytes. (`profile.trim-paths` is still unstable on 1.97.)
  const cargoHome = process.env.CARGO_HOME ?? join(homedir(), '.cargo');
  const rustflags = [process.env.RUSTFLAGS, `--remap-path-prefix=${cargoHome}=/cargo`]
    .filter(Boolean)
    .join(' ');
  execFileSync(
    'wasm-pack',
    ['build', '--release', '--target', 'web', '--out-dir', STAGING_DIR, '--out-name', 'vela_core', CRATE_DIR],
    { cwd: RUST_DIR, stdio: 'inherit', env: { ...process.env, RUSTFLAGS: rustflags } },
  );
}

/**
 * Replace the `import.meta.url` default-module-path fallback with a throw.
 * Metro cannot parse import.meta, and with base64 embedding the fallback is
 * dead code anyway — but it must be REMOVED, not just unused.
 *
 * Asserts the expected pattern exists first: if a wasm-bindgen upgrade changes
 * the glue, this fails loudly instead of silently shipping unpatched code.
 */
function patchGlue(js) {
  const pattern = /new URL\('vela_core_bg\.wasm', import\.meta\.url\)/g;
  const hits = js.match(pattern);
  if (!hits || hits.length === 0) {
    throw new Error(
      "build-web: wasm-bindgen glue no longer contains the expected `new URL('vela_core_bg.wasm', import.meta.url)` fallback — " +
        're-check the --target web output shape before shipping (research.md D7).',
    );
  }
  const patched = js.replace(
    pattern,
    "(() => { throw new Error('vela-core: module path lookup is unavailable in this bundle; call initSync with the embedded module'); })()",
  );
  if (/import\.meta/.test(patched)) {
    throw new Error(
      'build-web: `import.meta` still present in the patched glue — metro cannot bundle it. Inspect the remaining occurrences.',
    );
  }
  return patched;
}

function emit() {
  const wasm = readFileSync(join(STAGING_DIR, 'vela_core_bg.wasm'));
  if (wasm.byteLength > MAX_WASM_BYTES) {
    throw new Error(
      `build-web: wasm is ${wasm.byteLength} bytes, over the ${MAX_WASM_BYTES} ceiling. ` +
        'Switch to the async public/-dir loading route (research.md D7 fallback) instead of raising this limit.',
    );
  }
  const glue = patchGlue(readFileSync(join(STAGING_DIR, 'vela_core.js'), 'utf8'));
  const dts = readFileSync(join(STAGING_DIR, 'vela_core.d.ts'), 'utf8');

  const files = {
    'vela_core.js': glue,
    'vela_core.d.ts': dts,
    // Base64 payload kept in its own module so the (large) string never has to
    // be diffed alongside the glue.
    'vela_core_bg.base64.js':
      '// @generated by rust/scripts/build-web.mjs — do not edit.\n' +
      `export const WASM_BASE64 = '${wasm.toString('base64')}';\n`,
    'vela_core_bg.base64.d.ts': 'export declare const WASM_BASE64: string;\n',
    // Makes Node treat the generated .js as ESM so the corpus replay
    // (verify-web.mjs) can load the SHIPPED artifact directly. Metro uses its
    // own resolution and ignores this file.
    'package.json': JSON.stringify({ type: 'module', private: true }, null, 2) + '\n',
    'README.md':
      '# vela-core web build (generated)\n\n' +
      'Generated by `node rust/scripts/build-web.mjs` from `rust/crates/vela-core-wasm`.\n' +
      'Committed on purpose: metro cannot bundle wasm as ESM and Cloudflare Pages drops\n' +
      '`node_modules` asset paths, so the module ships base64-embedded and loads via\n' +
      '`initSync`. Do not hand-edit — CI (`node rust/scripts/build-web.mjs --check`)\n' +
      'fails if these files differ from a fresh build.\n',
  };

  if (CHECK_ONLY) {
    const drift = Object.entries(files).filter(([name, content]) => {
      const path = join(OUT_DIR, name);
      return !existsSync(path) || readFileSync(path, 'utf8') !== content;
    });
    const extra = existsSync(OUT_DIR)
      ? readdirSync(OUT_DIR).filter((n) => !(n in files))
      : [];
    if (drift.length || extra.length) {
      const names = [...drift.map(([n]) => n), ...extra.map((n) => `${n} (unexpected)`)];
      throw new Error(
        `build-web --check: rust/pkg-web is out of date (${names.join(', ')}). ` +
          'Run `npm run build:wasm` and commit the result.',
      );
    }
    console.log(`build-web --check: rust/pkg-web is current (wasm ${wasm.byteLength} bytes)`);
    return;
  }

  mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, content] of Object.entries(files)) {
    writeFileSync(join(OUT_DIR, name), content);
  }
  console.log(
    `build-web: wrote rust/pkg-web (wasm ${wasm.byteLength} bytes, base64 ${Math.round(
      (wasm.byteLength * 4) / 3 / 1024,
    )} KiB)`,
  );
}

buildWasm();
emit();
