<script lang="ts">
	/**
	 * The wallet exists.
	 *
	 * This is the first moment an address is shown, and that ordering is a rule
	 * rather than a layout choice: the core withholds `address` until the group
	 * has landed on-chain and the account is saved, because an address shown
	 * earlier is an address someone can fund before the wallet is reachable.
	 *
	 * The identicon is rendered from the address by the same core that derived
	 * it, so what the person memorises here is what every other client will
	 * draw.
	 */
	import Button from '$lib/ui/Button.svelte';
	import AddressStrip from '../AddressStrip.svelte';
	import { identiconNormalizeSeed, identiconSvgCircular } from '$lib/onboarding/core/wasm-client';
	import type { CreateKeyRow } from '$lib/onboarding/generated/CreateKeyRow';

	interface Props {
		address: string;
		walletName: string;
		keys: CreateKeyRow[];
		strings: (key: string, params?: Record<string, string | number>) => string;
		onEnter: () => void;
	}

	let { address, walletName, keys, strings, onEnter }: Props = $props();

	// The core owns seed normalization (spec 003's drift rule: never a local
	// toLowerCase). An unrenderable seed degrades to no artwork rather than
	// throwing on the one screen that must not fail.
	const identicon = $derived.by(() => {
		try {
			const seed = identiconNormalizeSeed(address);
			return seed.length === 0 ? null : identiconSvgCircular(seed);
		} catch {
			return null;
		}
	});
</script>

<section class="screen">
	<header class="intro">
		<div class="titlerow">
			<span class="tick" aria-hidden="true">
				<svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5" /></svg>
			</span>
			<h1 class="title">{strings('onboarding.create.successTitle')}</h1>
		</div>
		<p class="subtitle">{strings('onboarding.create.successMessage', { count: keys.length })}</p>
	</header>

	<div class="card">
		<div class="identity">
			<span class="avatar" aria-hidden="true">
				{#if identicon}
					<!-- eslint-disable-next-line svelte/no-at-html-tags -- SVG generated by vela-core from the address, never user input -->
					{@html identicon}
				{/if}
			</span>
			<span class="names">
				<span class="wallet">{walletName}</span>
				<span class="identityhint">{strings('onboarding.create.identiconHint')}</span>
			</span>
		</div>

		<div class="addressblock">
			<span class="addresslabel">{strings('onboarding.create.walletAddressLabel')}</span>
			<AddressStrip
				{address}
				copyLabel={strings('onboarding.common.copyAddress')}
				copiedLabel={strings('onboarding.common.copied')}
			/>
		</div>
	</div>

	<ul class="keys">
		{#each keys as key, index (index)}
			<li class="key">
				<span class="keyname">{key.name}</span>
				<span class="badge" data-tone={key.synced ? 'synced' : 'local'}>
					{key.synced
						? strings('onboarding.create.keySyncedBadge')
						: strings('onboarding.create.keyDeviceOnlyBadge')}
				</span>
			</li>
		{/each}
	</ul>

	<div class="spacer"></div>

	<Button variant="primary" shape="rounded" onclick={onEnter}>
		{strings('onboarding.create.enterWalletBtn')}
	</Button>
</section>

<style>
	.screen {
		display: flex;
		flex: 1;
		flex-direction: column;
		gap: var(--space-3xl);
	}

	.intro {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
	}

	.titlerow {
		display: flex;
		gap: var(--space-lg);
		align-items: center;
	}

	.tick {
		display: grid;
		flex: 0 0 var(--icon-xl);
		place-items: center;
		height: var(--icon-xl);
		border-radius: var(--radius-full);
		background: var(--color-success-soft);
	}

	.tick svg {
		width: var(--icon-base);
		height: var(--icon-base);
		fill: none;
		stroke: var(--color-success-base);
		stroke-width: var(--icon-stroke-heavy);
		stroke-linecap: round;
		stroke-linejoin: round;
	}

	.title {
		margin: 0;
		color: var(--color-fg-base);
		font-size: var(--text-3xl);
		font-weight: var(--weight-bold);
		line-height: var(--leading-tight);
		letter-spacing: -0.015em;
	}

	.subtitle {
		margin: 0;
		color: var(--color-fg-muted);
		font-size: var(--text-lg);
		line-height: var(--leading-normal);
	}

	.card {
		display: flex;
		flex-direction: column;
		gap: var(--space-xl);
		padding: var(--space-xl);
		border: var(--border-hairline) solid var(--color-border-base);
		border-radius: var(--radius-lg);
		background: var(--color-bg-sunken);
	}

	.identity {
		display: flex;
		gap: var(--space-xl);
		align-items: center;
	}

	.avatar {
		display: grid;
		flex: 0 0 var(--size-identiconDetail);
		place-items: center;
		width: var(--size-identiconDetail);
		height: var(--size-identiconDetail);
		border-radius: var(--radius-full);
		overflow: hidden;
	}

	.avatar :global(svg) {
		width: 100%;
		height: 100%;
	}

	.names {
		display: flex;
		flex-direction: column;
		gap: var(--space-xs);
		min-width: 0;
	}

	.wallet {
		color: var(--color-fg-base);
		font-size: var(--text-lg);
		font-weight: var(--weight-bold);
	}

	.identityhint {
		color: var(--color-fg-muted);
		font-size: var(--text-sm);
	}

	.addressblock {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
		padding-top: var(--space-lg);
		border-top: var(--border-hairline) solid var(--color-border-base);
	}

	.addresslabel {
		color: var(--color-fg-muted);
		font-size: var(--text-sm);
		font-weight: var(--weight-semibold);
		letter-spacing: 0.06em;
		text-transform: uppercase;
	}

	.keys {
		display: flex;
		flex-direction: column;
		margin: 0;
		padding: 0;
		list-style: none;
	}

	.key {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding-block: var(--space-lg);
		border-bottom: var(--border-hairline) solid var(--color-border-base);
	}

	.keyname {
		color: var(--color-fg-muted);
		font-size: var(--text-base);
	}

	.badge {
		font-size: var(--text-sm);
		font-weight: var(--weight-semibold);
	}

	.badge[data-tone='synced'] {
		color: var(--color-success-base);
	}

	.badge[data-tone='local'] {
		color: var(--color-warning-base);
	}

	.spacer {
		flex: 1;
		min-height: var(--space-md);
	}
</style>
