/**
 * The three intro illustrations — the web port of
 * `specs/020-intro-carousel/contracts/intro-illustrations.json`.
 *
 * Hand-ported, like the lucide corpus in `$lib/wallet/icons.ts`: the contract is
 * generated by `scripts/gen-intro-art.mjs` from measurements of the design
 * boards, and each of the four apps re-expresses it in whatever its renderer
 * speaks. Here that is an inline `<svg>` and `currentColor` is not enough,
 * because a single drawing carries two colours — the line work and the one
 * accent thing the slide is about.
 *
 * `intro-art.test.ts` re-reads the contract and asserts these paths still match
 * it, so a regenerated contract fails here rather than on somebody's screen.
 */

export type IntroArtRole = 'line' | 'accent';

export type IntroArtElement = {
	role: IntroArtRole;
	/**
	 * `stroke` and `fill` are what they say. `outline` is filled with the PAGE
	 * background and then stroked — it sits over the drawing and hides what is
	 * behind it, which is how the compass needle's southern half reads as the
	 * same needle rather than a second one.
	 */
	mode: 'stroke' | 'fill' | 'outline';
	width?: number;
	opacity: number;
	d: string;
};

export type IntroArtId = 'no-seed-phrase' | 'keys-are-yours' | 'one-address';

/** Every illustration is drawn in this box, so paging never resizes the art. */
export const INTRO_ART_VIEWBOX = { width: 160, height: 128 } as const;

export const INTRO_ART: Record<IntroArtId, readonly IntroArtElement[]> = {
	// 1 · A form whose rules fade out, and the fingerprint that replaces it.
	'no-seed-phrase': [
		{
			role: 'line',
			mode: 'stroke',
			width: 1.5,
			opacity: 0.85,
			d: 'M11 3H95.5A10 10 0 0 1 105.5 13V115A10 10 0 0 1 95.5 125H11A10 10 0 0 1 1 115V13A10 10 0 0 1 11 3Z'
		},
		{
			role: 'line',
			mode: 'stroke',
			width: 2.5,
			opacity: 0.7,
			d: 'M17.25 25L48.75 25M59.25 25L84.75 25'
		},
		{
			role: 'line',
			mode: 'stroke',
			width: 2.5,
			opacity: 0.6,
			d: 'M17.25 42L52.75 42M59.25 42L80.75 42'
		},
		{
			role: 'line',
			mode: 'stroke',
			width: 2.5,
			opacity: 0.5,
			d: 'M17.25 59L44.75 59M59.25 59L88.75 59'
		},
		{
			role: 'line',
			mode: 'stroke',
			width: 2.5,
			opacity: 0.4,
			d: 'M17.25 76L50.75 76M59.25 76L82.75 76'
		},
		{
			role: 'line',
			mode: 'stroke',
			width: 2.5,
			opacity: 0.3,
			d: 'M17.25 93L46.75 93M59.25 93L78.75 93'
		},
		{
			role: 'line',
			mode: 'stroke',
			width: 2.5,
			opacity: 0.2,
			d: 'M17.25 110L42.75 110M59.25 110L86.75 110'
		},
		{
			role: 'accent',
			mode: 'stroke',
			width: 2,
			opacity: 1,
			d: 'M121.15 76.91A6.5 8.2 0 1 1 119.87 87.1M115.84 72.03A13 16.4 0 1 1 112.57 81.29M111.71 65.61A19.5 24.6 0 1 1 106.24 79.15M111.34 55.49A26 32.8 0 1 1 108.1 107.38M102.98 99.4A26 32.8 0 0 1 106.18 61.05M105.05 51.14A32.5 41 0 1 1 93.04 80.85'
		},
		{
			role: 'accent',
			mode: 'fill',
			opacity: 1,
			d: 'M123.9 83A1.6 1.6 0 0 1 127.1 83A1.6 1.6 0 0 1 123.9 83'
		}
	],

	// 2 · One ring, three keys — yours in the accent, the others still yours.
	'keys-are-yours': [
		{
			role: 'line',
			mode: 'stroke',
			width: 2,
			opacity: 1,
			d: 'M48.5 33.5A30.5 30.5 0 0 1 109.5 33.5A30.5 30.5 0 0 1 48.5 33.5'
		},
		{
			role: 'line',
			mode: 'stroke',
			width: 1.5,
			opacity: 0.45,
			d: 'M90.57 55.07A10 10 0 0 1 110.57 55.07A10 10 0 0 1 90.57 55.07M107.64 62.14L133.45 87.95M126.02 80.52L130.27 76.28M130.8 85.3L136.1 79.99M47.43 55.07A10 10 0 0 1 67.43 55.07A10 10 0 0 1 47.43 55.07M50.36 62.14L24.55 87.95M31.98 80.52L36.22 84.77M27.2 85.3L32.51 90.6'
		},
		{
			role: 'accent',
			mode: 'stroke',
			width: 3.5,
			opacity: 1,
			d: 'M79 74L79 126M79 112L87 112M79 121L89 121'
		},
		{
			role: 'accent',
			mode: 'stroke',
			width: 4,
			opacity: 1,
			d: 'M69 64A10 10 0 0 1 89 64A10 10 0 0 1 69 64'
		},
		{
			role: 'accent',
			mode: 'stroke',
			width: 3,
			opacity: 1,
			d: 'M75.5 64A3.5 3.5 0 0 1 82.5 64A3.5 3.5 0 0 1 75.5 64'
		}
	],

	// 3 · A compass: one bearing, and it holds on every chain.
	'one-address': [
		{
			role: 'line',
			mode: 'stroke',
			width: 1.5,
			opacity: 0.85,
			d: 'M19.5 64A60.5 60.5 0 0 1 140.5 64A60.5 60.5 0 0 1 19.5 64'
		},
		{
			role: 'line',
			mode: 'stroke',
			width: 1.8,
			opacity: 0.85,
			d: 'M75.5 23.5L75.5 10.5L84.5 23.5L84.5 10.5'
		},
		{
			role: 'line',
			mode: 'fill',
			opacity: 1,
			d: 'M126.5 64A3 3 0 0 1 132.5 64A3 3 0 0 1 126.5 64M77 113.5A3 3 0 0 1 83 113.5A3 3 0 0 1 77 113.5M27.5 64A3 3 0 0 1 33.5 64A3 3 0 0 1 27.5 64'
		},
		{
			role: 'line',
			mode: 'fill',
			opacity: 0.55,
			d: 'M120.37 88.75A2.5 2.5 0 0 1 125.37 88.75A2.5 2.5 0 0 1 120.37 88.75M102.25 106.87A2.5 2.5 0 0 1 107.25 106.87A2.5 2.5 0 0 1 102.25 106.87M52.75 106.87A2.5 2.5 0 0 1 57.75 106.87A2.5 2.5 0 0 1 52.75 106.87M34.63 88.75A2.5 2.5 0 0 1 39.63 88.75A2.5 2.5 0 0 1 34.63 88.75M35.13 39.25A2 2 0 0 1 39.13 39.25A2 2 0 0 1 35.13 39.25M53.5 21.13A1.75 1.75 0 0 1 57 21.13A1.75 1.75 0 0 1 53.5 21.13M103 21.13A1.75 1.75 0 0 1 106.5 21.13A1.75 1.75 0 0 1 103 21.13M120.87 39.25A2 2 0 0 1 124.87 39.25A2 2 0 0 1 120.87 39.25'
		},
		{
			role: 'accent',
			mode: 'fill',
			opacity: 1,
			d: 'M70.86 60.43L97.12 26.04L89.14 68.57Z'
		},
		{
			role: 'line',
			mode: 'outline',
			width: 1.2,
			opacity: 0.8,
			d: 'M70.86 60.43L63.16 102.32L89.14 68.57Z'
		},
		{
			role: 'accent',
			mode: 'outline',
			width: 2,
			opacity: 1,
			d: 'M75.5 64.5A4.5 4.5 0 0 1 84.5 64.5A4.5 4.5 0 0 1 75.5 64.5'
		}
	]
};
