//! Who is holding this passkey — resolved from the authenticator's AAGUID.
//!
//! Every registration reports a 128-bit AAGUID identifying the authenticator
//! MODEL (never the person, never the key). `iCloud 钥匙串`, `1Password`,
//! `Windows Hello`, `Samsung Pass` — that is the fact a key list needs, because
//! "where does this passkey live" is the question somebody is actually asking
//! when they look at one, and `此设备上的通行密钥` answers it for every key at
//! once.
//!
//! **The catalog is vendored, not queried.** aaguid-explorer.awesometools.dev
//! offers this lookup over HTTP; asking it would tell a third party which vault
//! holds a Vela wallet's key, which is exactly the kind of thing this wallet
//! exists not to leak. The table is compiled in
//! ([`passkey_catalog`](crate::passkey_catalog)), generated by
//! `scripts/gen-passkey-providers.mjs` from a reviewed file in the repo.
//!
//! **A miss is a normal answer, not an error.** The catalog covers software
//! passkey providers, not the hundreds of hardware models in the FIDO metadata
//! service, and an authenticator may report an all-zero AAGUID when attestation
//! is `none`. Callers degrade to what they already know — platform vs
//! cross-platform, the transports — which is what every client did before this
//! module existed.

use crate::passkey_catalog::{ICONS, NO_ICON, PROVIDERS};

/// A resolved authenticator model.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PasskeyProvider {
    /// The canonical AAGUID, lowercase.
    pub aaguid: &'static str,
    /// The provider's own brand name, verbatim. NOT translated: "1Password" is
    /// "1Password" in every locale, and a translated brand is a wrong brand.
    pub name: &'static str,
    light: u16,
    dark: u16,
}

impl PasskeyProvider {
    /// The provider's mark as SVG markup for the given theme, falling back to
    /// the other theme's mark when only one is published.
    #[must_use]
    pub fn icon_svg(&self, dark: bool) -> Option<&'static str> {
        let (first, second) = if dark {
            (self.dark, self.light)
        } else {
            (self.light, self.dark)
        };
        for index in [first, second] {
            if index != NO_ICON {
                return ICONS.get(index as usize).copied();
            }
        }
        None
    }
}

/// Resolve an AAGUID to its provider. Input may be any case, with or without
/// surrounding whitespace; an empty or all-zero AAGUID resolves to `None`.
#[must_use]
pub fn provider(aaguid: &str) -> Option<PasskeyProvider> {
    let key = aaguid.trim().to_ascii_lowercase();
    if key.is_empty() || key.bytes().all(|b| b == b'0' || b == b'-') {
        return None;
    }
    let position = PROVIDERS
        .binary_search_by(|(candidate, ..)| (*candidate).cmp(key.as_str()))
        .ok()?;
    let (aaguid, name, light, dark) = PROVIDERS[position];
    Some(PasskeyProvider {
        aaguid,
        name,
        light,
        dark,
    })
}

/// The provider's brand name, or `None` when the catalog does not know it.
#[must_use]
pub fn provider_name(aaguid: &str) -> Option<&'static str> {
    provider(aaguid).map(|p| p.name)
}

/// The provider's mark as an `image/svg+xml` data URI.
///
/// A data URI rather than markup to inline: these SVGs carry `<style>` blocks
/// with generic class names (`.cls-1`) and `<clipPath id="…">`, so inlining
/// several of them into one document makes the last one's rules win for all of
/// them — the same id/class collision that once turned this app's identicons
/// square. Inside an `<img>`, each mark is its own document.
#[must_use]
pub fn provider_icon_data_uri(aaguid: &str, dark: bool) -> Option<String> {
    let svg = provider(aaguid)?.icon_svg(dark)?;
    Some(format!(
        "data:image/svg+xml;charset=utf-8,{}",
        percent_encode(svg)
    ))
}

/// Minimal percent-encoding for SVG in a data URI: only what a URI parser or an
/// HTML attribute would otherwise take for its own.
fn percent_encode(svg: &str) -> String {
    let mut out = String::with_capacity(svg.len() + svg.len() / 8);
    for byte in svg.bytes() {
        match byte {
            b'#' | b'%' | b'"' | b'\'' | b'<' | b'>' | b'?' | b'&' | b' ' => {
                out.push_str(&format!("%{byte:02X}"));
            }
            _ => out.push(byte as char),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_catalog_is_sorted_and_canonical() {
        for window in PROVIDERS.windows(2) {
            assert!(window[0].0 < window[1].0, "PROVIDERS must be sorted");
        }
        for (aaguid, name, ..) in PROVIDERS {
            assert_eq!(aaguid.len(), 36, "canonical uuid: {aaguid}");
            assert!(!name.is_empty(), "every provider is named");
        }
    }

    #[test]
    fn well_known_providers_resolve_in_any_case() {
        // Two the whole world sees; if the vendored file ever loses them, the
        // feature is silently useless for most people.
        assert_eq!(
            provider_name("fbfc3007-154e-4ecc-8c0b-6e020557d7bd"),
            // The dataset's own current name — Apple renamed it from iCloud
            // Keychain, and this catalog says what the vendor says.
            Some("Apple Passwords")
        );
        assert_eq!(
            provider_name("EA9B8D66-4D01-1D21-3CE4-B6B48CB575D4"),
            Some("Google Password Manager")
        );
        assert_eq!(
            provider_name("  08987058-cadc-4b81-b6e1-30de50dcbe96  "),
            Some("Windows Hello")
        );
    }

    #[test]
    fn a_miss_is_none_not_a_wrong_guess() {
        assert_eq!(provider_name(""), None);
        assert_eq!(provider_name("00000000-0000-0000-0000-000000000000"), None);
        assert_eq!(provider_name("not-a-uuid"), None);
        // A real YubiKey AAGUID: hardware keys live in the FIDO metadata
        // service, which this catalog deliberately does not carry.
        assert_eq!(provider_name("2fc0579f-8113-47ea-b116-bb5a8db9202a"), None);
    }

    #[test]
    fn every_provider_has_a_mark_in_both_themes() {
        for (aaguid, name, ..) in PROVIDERS {
            let p = provider(aaguid).expect("catalog entry resolves");
            // Two of the 55 publish no artwork at all; the rest must answer for
            // both themes (falling back across themes when only one exists).
            if p.icon_svg(false).is_none() {
                assert!(p.icon_svg(true).is_none(), "{name}: one-sided fallback");
            }
        }
    }

    #[test]
    fn data_uris_escape_what_an_attribute_would_eat() {
        let uri = provider_icon_data_uri("fbfc3007-154e-4ecc-8c0b-6e020557d7bd", false)
            .expect("Apple Passwords ships a mark");
        assert!(uri.starts_with("data:image/svg+xml;charset=utf-8,"));
        assert!(!uri.contains('"'), "quotes would close the src attribute");
        assert!(!uri.contains('#'), "a hash would truncate the URI");
        assert!(!uri.contains('<'), "angle brackets would reopen the markup");
    }
}
