//! GENERATED by scripts/gen-i18n.mjs — do not edit by hand.
//!
//! One compiled-in value table per locale, each behind its own cargo feature so a
//! build carries only the languages it ships (FR-014). Locales not compiled in are
//! still reachable at runtime through `Catalog::from_json` (FR-015), which is the
//! route the web build uses for all of them.

#[cfg(feature = "i18n-en")]
pub(crate) mod en;
#[cfg(feature = "i18n-zh")]
pub(crate) mod zh;
#[cfg(feature = "i18n-zh-tw")]
pub(crate) mod zh_tw;
#[cfg(feature = "i18n-zh-hk")]
pub(crate) mod zh_hk;
#[cfg(feature = "i18n-ja")]
pub(crate) mod ja;
#[cfg(feature = "i18n-ko")]
pub(crate) mod ko;
#[cfg(feature = "i18n-vi")]
pub(crate) mod vi;
#[cfg(feature = "i18n-id")]
pub(crate) mod id;
#[cfg(feature = "i18n-tr")]
pub(crate) mod tr;
#[cfg(feature = "i18n-es-mx")]
pub(crate) mod es_mx;
#[cfg(feature = "i18n-pt-br")]
pub(crate) mod pt_br;
#[cfg(feature = "i18n-fr")]
pub(crate) mod fr;
#[cfg(feature = "i18n-de")]
pub(crate) mod de;
#[cfg(feature = "i18n-ru")]
pub(crate) mod ru;
#[cfg(feature = "i18n-it")]
pub(crate) mod it;

/// The compiled-in table for `lang`, if its feature is enabled.
///
/// Returns `(blob, offsets, present)`.
pub(crate) fn embedded(lang: &str) -> Option<(&'static str, &'static [u16], &'static [u8])> {
    match lang {
        #[cfg(feature = "i18n-en")]
        "en" => Some((en::BLOB, &en::OFFSETS, &en::PRESENT)),
        #[cfg(feature = "i18n-zh")]
        "zh" => Some((zh::BLOB, &zh::OFFSETS, &zh::PRESENT)),
        #[cfg(feature = "i18n-zh-tw")]
        "zh-TW" => Some((zh_tw::BLOB, &zh_tw::OFFSETS, &zh_tw::PRESENT)),
        #[cfg(feature = "i18n-zh-hk")]
        "zh-HK" => Some((zh_hk::BLOB, &zh_hk::OFFSETS, &zh_hk::PRESENT)),
        #[cfg(feature = "i18n-ja")]
        "ja" => Some((ja::BLOB, &ja::OFFSETS, &ja::PRESENT)),
        #[cfg(feature = "i18n-ko")]
        "ko" => Some((ko::BLOB, &ko::OFFSETS, &ko::PRESENT)),
        #[cfg(feature = "i18n-vi")]
        "vi" => Some((vi::BLOB, &vi::OFFSETS, &vi::PRESENT)),
        #[cfg(feature = "i18n-id")]
        "id" => Some((id::BLOB, &id::OFFSETS, &id::PRESENT)),
        #[cfg(feature = "i18n-tr")]
        "tr" => Some((tr::BLOB, &tr::OFFSETS, &tr::PRESENT)),
        #[cfg(feature = "i18n-es-mx")]
        "es-MX" => Some((es_mx::BLOB, &es_mx::OFFSETS, &es_mx::PRESENT)),
        #[cfg(feature = "i18n-pt-br")]
        "pt-BR" => Some((pt_br::BLOB, &pt_br::OFFSETS, &pt_br::PRESENT)),
        #[cfg(feature = "i18n-fr")]
        "fr" => Some((fr::BLOB, &fr::OFFSETS, &fr::PRESENT)),
        #[cfg(feature = "i18n-de")]
        "de" => Some((de::BLOB, &de::OFFSETS, &de::PRESENT)),
        #[cfg(feature = "i18n-ru")]
        "ru" => Some((ru::BLOB, &ru::OFFSETS, &ru::PRESENT)),
        #[cfg(feature = "i18n-it")]
        "it" => Some((it::BLOB, &it::OFFSETS, &it::PRESENT)),
        _ => None,
    }
}
