import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 950 }, deviceScaleFactor: 2 });
const go = async (path, ms) => { await p.evaluate((u) => { history.pushState({}, '', u); window.dispatchEvent(new PopStateEvent('popstate', { state: {} })); }, path); await p.waitForTimeout(ms||2500); };
const texts = async () => p.evaluate(() => {
  const f = [...document.querySelectorAll('div')].find(d => { const r=d.getBoundingClientRect(); return Math.abs(r.width-390)<=2 && r.height>600; });
  return f ? [...f.querySelectorAll('*')].filter(e=>e.children.length===0&&(e.textContent||'').trim()).map(e=>e.textContent.trim()) : [];
});
await p.goto('http://127.0.0.1:8083/parallel', { waitUntil: 'networkidle', timeout: 60000 });
await p.waitForTimeout(6000);
await p.evaluate(() => { window.vela.clear(); window.vela.failRpc('all'); });
await go('/parallel/connect', 1800);
await go('/parallel', 3000);
await p.waitForTimeout(13000);
const t1 = await texts();
console.log('after nav+13s:', JSON.stringify(t1.slice(0, 30)));
console.log('has banner words:', t1.filter(x => /rpc|unavailable|fix|couldn|retry|estimate|failing/i.test(x)));
await p.screenshot({ path: '/tmp/exp2-rpc.png' });
await p.waitForTimeout(12000);
const t2 = await texts();
console.log('after +12s:', t2.filter(x => /rpc|unavailable|fix|couldn|retry|estimate|failing/i.test(x)));
await p.screenshot({ path: '/tmp/exp2-rpc-late.png' });
await b.close();
